### ISSUE TITLE
Where could I get *.pkl files to execute "0_data_preprocessing_broad.ipynb"?

### ISSUE THREAD

**Issue by DavidChoi76** [mashrekur/topic_modeling_hydrology#1]
This research is very interesting to me, so I want to try to execute this code by myself.

I'm a little bit confused of execution process.
When I execute a code in "0_data_preprocessing_broad.ipynb", I got an error 
`# # load preprocessed corpus for original static topic model`
`with open('data/raw_corpus_broad_country.pkl', 'rb') as f:`
         `corpus_df = pickle.load(f)`

`"FileNotFoundError: [Errno 2] No such file or directory: 'data/raw_corpus_broad_country.pkl'"`

Where can I get "raw_corpus_broad_country.pkl" file?

My understanding from README.md is "0_data_preprocessing_broad.ipynb" produces four outputs: (i) raw_corpus_broad_country.pkl, (ii) data_lemmatized.pkl, (iii) id2word.pkl, (iv) cleaned_corpus.pkl. 

Which are correct?

Thanks for your help.

**Comment by mashrekur** [comment]
Hello Choi

Thanks for your query. That line of code should be commented out. We put it in there to save computational time because we had a preprocessed corpus. You can delete these lines. 

Also, the preprocessed pickle file you are referring to is not available through GitHub due to file size and data sharing restrictions. But you can create your own custom corpus (set of text documents for your analysis). 

Article abstracts and corresponding metadata are available through multiple sources. We used Web of Science core collection and Lens.org to get hydrology article-abstracts and metadata between 1991 and 2019. 

Please let me know if you have any other questions.

Thanks
Mashrekur Rahman
